title: 3407 Wild Cards
description: FRC Team 3407's website for information and events.
remote_theme: "jekyll/minima@1e8a445"

github:
  is_project_page: false
exclude:
  - README.md
  - LICENSE
header_pages:
  -jEvents.md
  -kSponsors.md
  -lProspective-Members.md
